version: '3.7'
services: 
  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes: 
      - .:/app
      - bundle-volume:/usr/local/bundle
    ports:
      - "3000:3000"
    depends_on: 
      - db

  db: 
    environment: 
      POSTGRES_PASSWORD: password123
    image: "postgres:12"
    ports: 
      - "5430:5432"
    volumes: 
      - "db-volume:/var/lib/postgresql/data"

volumes:
  db-volume:
  bundle-volume:
